// <auto-generated />
using CartesianExplosion;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartesianExplosion.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240526075033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("CartesianExplosion.JoinTable1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryTableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTableId");

                    b.ToTable("JoinTable1s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 2,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 3,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 4,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 5,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 6,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 7,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 8,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 9,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 10,
                            PrimaryTableId = 1
                        });
                });

            modelBuilder.Entity("CartesianExplosion.JoinTable2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryTableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTableId");

                    b.ToTable("JoinTable2s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 2,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 3,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 4,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 5,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 6,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 7,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 8,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 9,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 10,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 11,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 12,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 13,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 14,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 15,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 16,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 17,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 18,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 19,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 20,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 21,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 22,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 23,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 24,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 25,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 26,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 27,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 28,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 29,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 30,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 31,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 32,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 33,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 34,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 35,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 36,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 37,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 38,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 39,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 40,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 41,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 42,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 43,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 44,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 45,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 46,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 47,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 48,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 49,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 50,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 51,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 52,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 53,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 54,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 55,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 56,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 57,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 58,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 59,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 60,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 61,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 62,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 63,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 64,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 65,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 66,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 67,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 68,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 69,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 70,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 71,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 72,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 73,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 74,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 75,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 76,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 77,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 78,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 79,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 80,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 81,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 82,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 83,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 84,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 85,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 86,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 87,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 88,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 89,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 90,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 91,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 92,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 93,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 94,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 95,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 96,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 97,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 98,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 99,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 100,
                            PrimaryTableId = 1
                        });
                });

            modelBuilder.Entity("CartesianExplosion.JoinTable3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryTableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTableId");

                    b.ToTable("JoinTable3s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 2,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 3,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 4,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 5,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 6,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 7,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 8,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 9,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 10,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 11,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 12,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 13,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 14,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 15,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 16,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 17,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 18,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 19,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 20,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 21,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 22,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 23,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 24,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 25,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 26,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 27,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 28,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 29,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 30,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 31,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 32,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 33,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 34,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 35,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 36,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 37,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 38,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 39,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 40,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 41,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 42,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 43,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 44,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 45,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 46,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 47,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 48,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 49,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 50,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 51,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 52,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 53,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 54,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 55,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 56,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 57,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 58,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 59,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 60,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 61,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 62,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 63,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 64,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 65,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 66,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 67,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 68,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 69,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 70,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 71,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 72,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 73,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 74,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 75,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 76,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 77,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 78,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 79,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 80,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 81,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 82,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 83,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 84,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 85,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 86,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 87,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 88,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 89,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 90,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 91,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 92,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 93,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 94,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 95,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 96,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 97,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 98,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 99,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 100,
                            PrimaryTableId = 1
                        });
                });

            modelBuilder.Entity("CartesianExplosion.JoinTable4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryTableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTableId");

                    b.ToTable("JoinTable4s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 2,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 3,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 4,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 5,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 6,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 7,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 8,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 9,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 10,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 11,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 12,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 13,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 14,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 15,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 16,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 17,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 18,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 19,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 20,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 21,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 22,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 23,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 24,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 25,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 26,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 27,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 28,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 29,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 30,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 31,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 32,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 33,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 34,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 35,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 36,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 37,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 38,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 39,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 40,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 41,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 42,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 43,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 44,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 45,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 46,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 47,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 48,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 49,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 50,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 51,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 52,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 53,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 54,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 55,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 56,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 57,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 58,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 59,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 60,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 61,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 62,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 63,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 64,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 65,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 66,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 67,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 68,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 69,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 70,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 71,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 72,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 73,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 74,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 75,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 76,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 77,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 78,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 79,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 80,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 81,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 82,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 83,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 84,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 85,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 86,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 87,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 88,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 89,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 90,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 91,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 92,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 93,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 94,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 95,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 96,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 97,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 98,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 99,
                            PrimaryTableId = 1
                        },
                        new
                        {
                            Id = 100,
                            PrimaryTableId = 1
                        });
                });

            modelBuilder.Entity("CartesianExplosion.PrimaryTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrimaryTables");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("CartesianExplosion.JoinTable1", b =>
                {
                    b.HasOne("CartesianExplosion.PrimaryTable", null)
                        .WithMany("JoinTable1s")
                        .HasForeignKey("PrimaryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartesianExplosion.JoinTable2", b =>
                {
                    b.HasOne("CartesianExplosion.PrimaryTable", null)
                        .WithMany("JoinTable2s")
                        .HasForeignKey("PrimaryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartesianExplosion.JoinTable3", b =>
                {
                    b.HasOne("CartesianExplosion.PrimaryTable", null)
                        .WithMany("JoinTable3s")
                        .HasForeignKey("PrimaryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartesianExplosion.JoinTable4", b =>
                {
                    b.HasOne("CartesianExplosion.PrimaryTable", null)
                        .WithMany("JoinTable4s")
                        .HasForeignKey("PrimaryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CartesianExplosion.PrimaryTable", b =>
                {
                    b.Navigation("JoinTable1s");

                    b.Navigation("JoinTable2s");

                    b.Navigation("JoinTable3s");

                    b.Navigation("JoinTable4s");
                });
#pragma warning restore 612, 618
        }
    }
}
